//
//  LoginScreenPresenter.swift
//  Rager Streak
//
//  Created by guilherme.martinelli on 16/11/20.
//  Copyright (c) 2020 guilherme.martinelli. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//

import UIKit

protocol LoginScreenPresentationLogic {
    func passwordCorrect()
    func passwordIncorrect()
}

class LoginScreenPresenter: LoginScreenPresentationLogic {
    
  weak var viewController: LoginScreenDisplayLogic?
    
  func passwordCorrect() {
    viewController?.passwordCorrect()
  }
  
  func passwordIncorrect() {
      let viewModel = LoginScreen.Model.LabelViewModel(textMessage: "A palavra-chave está incorreta!", colorMessage: .red)
      viewController?.passwordIncorrect(textFieldViewModel: viewModel)
  }
  
}
