//
//  LoginScreenViewController.swift
//  Rager Streak
//
//  Created by guilherme.martinelli on 16/11/20.
//  Copyright (c) 2020 guilherme.martinelli. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//

import UIKit

protocol LoginScreenDisplayLogic: class {
    func changeText(textFieldViewModel: LoginScreen.Model.LabelViewModel)
}

class LoginScreenViewController: UIViewController, LoginScreenDisplayLogic {
    
    @IBOutlet weak var password: UITextField!
    @IBOutlet weak var message: UILabel!
    var interactor: LoginScreenBusinessLogic?
    
    // MARK: Object lifecycle
    override init(nibName nibNameOrNil: String?, bundle nibBundleOrNil: Bundle?) {
        super.init(nibName: nibNameOrNil, bundle: nibBundleOrNil)
        setup()
    }
    
    required init?(coder aDecoder: NSCoder) {
        super.init(coder: aDecoder)
        setup()
    }
    
    // MARK: Setup
    private func setup() {
        let viewController = self
        let interactor = LoginScreenInteractor()
        let presenter = LoginScreenPresenter()
        
        viewController.interactor = interactor
        interactor.presenter = presenter
        presenter.viewController = viewController
        
    }
    
    // MARK: View lifecycle
    override func viewDidLoad() {
        super.viewDidLoad()
        
    }
    
    // MARK: Do something
    func changeText(textFieldViewModel: LoginScreen.Model.LabelViewModel) {
        message.changeText(string: textFieldViewModel.textMessage,
                           color: textFieldViewModel.colorMessage)
    }
    
    @IBAction func confirmPassword(_ sender: Any) {
        interactor?.confirmPassword(string: password.text)
    }
}
