//
//  SecondScreenPresenter.swift
//  Rager Streak
//
//  Created by guilherme.martinelli on 16/11/20.
//  Copyright (c) 2020 guilherme.martinelli. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//

import UIKit

protocol LoginScreenPresentationLogic
{
    func setupButtonAndInputs()
}

class LoginScreenPresenter: LoginScreenPresentationLogic
{
    
    weak var viewController: LoginScreenDisplayLogic?
    // MARK: Do something
    func setupButtonAndInputs() {
        //inputs
        let userPlaceHolder = RSTextField().setPlaceHolderColor(string: "Digite seu usuário", opacity: 0.9)
        let passwordPlaceHolder = RSTextField().setPlaceHolderColor(string: "Digite sua senha", opacity: 0.9)
        let viewModelInput = FirstScreen.Model.RSInput(userPlaceHolder: userPlaceHolder,
                                                       passwordPlaceHolder: passwordPlaceHolder)
        viewController?.setupInput(viewModelInput: viewModelInput)
    }

}
