//
//  LoginScreenInteractor.swift
//  Rager Streak
//
//  Created by guilherme.martinelli on 16/11/20.
//  Copyright (c) 2020 guilherme.martinelli. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//

import UIKit

protocol LoginScreenBusinessLogic
{
    func setupButton()
}

protocol LoginScreenDataStore {
     var user: LoginScreen.Model.User? { get set }
}

class LoginScreenInteractor: LoginScreenBusinessLogic, LoginScreenDataStore {
    
    var user: LoginScreen.Model.User?
    var presenter: LoginScreenPresentationLogic?

    // MARK: Do something
    func setupButton() {
        presenter?.setupButton()
    }
  
}
