//
//  LoginScreenViewController.swift
//  Rager Streak
//
//  Created by guilherme.martinelli on 16/11/20.
//  Copyright (c) 2020 guilherme.martinelli. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//

import UIKit

protocol LoginScreenDisplayLogic: class {
    func routeToSecondScreen()
    func setupButton(buttonViewModel: LoginScreen.Model.RSButton)
}

class LoginScreenViewController: UIViewController, LoginScreenDisplayLogic {
    
    @IBOutlet weak var buttonReady: UIButton!
    @IBOutlet weak var message: UILabel!
    var interactor: LoginScreenBusinessLogic?
    var router: (NSObjectProtocol & LoginScreenRoutingLogic & LoginScreenDataPassing)?
    
    // MARK: Object lifecycle
    override init(nibName nibNameOrNil: String?, bundle nibBundleOrNil: Bundle?) {
        super.init(nibName: nibNameOrNil, bundle: nibBundleOrNil)
        setup()
    }
    
    required init?(coder aDecoder: NSCoder) {
        super.init(coder: aDecoder)
        setup()
    }
    
    // MARK: Setup
    private func setup() {
        let viewController = self
        let interactor = LoginScreenInteractor()
        let presenter = LoginScreenPresenter()
        let router = LoginScreenRouter()
        viewController.interactor = interactor
        viewController.router = router
        interactor.presenter = presenter
        presenter.viewController = viewController
        router.viewController = viewController
        router.dataStore = interactor
        
    }
    
    // MARK: View lifecycle
    override func viewDidLoad() {
        super.viewDidLoad()
        self.navigationController?.setNavigationBarHidden(true, animated: false)
        view.backgroundColor = UIColor(hexString: "131313")
        interactor?.setupButton()
    }
    
    override func viewWillAppear(_ animated: Bool) {
        self.navigationController?.setNavigationBarHidden(true, animated: false)
    }
    // MARK: Do something
    func routeToSecondScreen() {
        router?.routeToSuccess()
    }
    
    func setupButton(buttonViewModel: LoginScreen.Model.RSButton) {
        buttonReady.layer.borderColor = buttonViewModel.borderColor
        buttonReady.layer.borderWidth = buttonViewModel.borderWidth
    }
    
    func passwordIncorrect(textFieldViewModel: LoginScreen.Model.LabelViewModel) {
        message.changeText(string: textFieldViewModel.textMessage,
                           color: textFieldViewModel.colorMessage)
    }
    
    @IBAction func confirmPassword(_ sender: Any) {
        routeToSecondScreen()
    }
}
