//
//  LoginScreenPresenter.swift
//  Rager Streak
//
//  Created by guilherme.martinelli on 16/11/20.
//  Copyright (c) 2020 guilherme.martinelli. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//

import UIKit

protocol LoginScreenPresentationLogic {
    func setupButton()
}

class LoginScreenPresenter: LoginScreenPresentationLogic {
    
  weak var viewController: LoginScreenDisplayLogic?
    
    func setupButton() {
        let color = UIColor(hexString: "7A4DDF").cgColor
        let viewModel = LoginScreen.Model.RSButton(borderColor: color, borderWidth: 2)
        viewController?.setupButton(buttonViewModel: viewModel)
    }
  
}
