//
//  LoginScreenInteractor.swift
//  Rager Streak
//
//  Created by guilherme.martinelli on 16/11/20.
//  Copyright (c) 2020 guilherme.martinelli. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//

import UIKit

protocol LoginScreenBusinessLogic
{
    func confirmPassword(string: String?)
}

class LoginScreenInteractor: LoginScreenBusinessLogic {
    
    var presenter: LoginScreenPresentationLogic?

    // MARK: Do something
    func confirmPassword(string: String?) {
        string == "Gui" ? presenter?.passwordCorrect() : presenter?.passwordIncorrect()
    }
  
}
