//
//  RagersRouter.swift
//  Rager Streak
//
//  Created by guilherme.martinelli on 15/12/20.
//  Copyright (c) 2020 guilherme.martinelli. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//

import UIKit

@objc protocol RagersRoutingLogic {
  func routeToSuccess()
}

protocol RagersDataPassing {
  var dataStore: RagersDataStore? { get }
}

class RagersRouter: NSObject, RagersRoutingLogic, RagersDataPassing {
  weak var viewController: RagersViewController?
  var dataStore: RagersDataStore?
  
  // MARK: Routing
  
    func routeToSuccess() {
        let destination: NewRagerViewController = UIStoryboard(name: "NewRager", bundle: nil).instantiateViewController(withIdentifier: "NewRagerViewController") as! NewRagerViewController
        viewController?.navigationController?.pushViewController(destination, animated: true)
//        viewController?.present(destination, animated: true, completion: nil)
    }
}
