//
//  FirstScreenRouter.swift
//  Rager Streak
//
//  Created by guilherme.martinelli on 16/11/20.
//  Copyright (c) 2020 guilherme.martinelli. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//

import UIKit

@objc protocol FirstScreenRoutingLogic
{
    func routeToSuccess()
}

protocol FirstScreenDataPassing
{
    var dataStore: FirstScreenDataStore? { get set }
}

class FirstScreenRouter: NSObject, FirstScreenRoutingLogic, FirstScreenDataPassing
{
    weak var viewController: FirstScreenViewController?
    var dataStore: FirstScreenDataStore?
    
    func routeToSuccess() {
        let destination: LoginScreenViewController = UIStoryboard(name: "SecondScreen", bundle: nil).instantiateViewController(withIdentifier: "LoginScreenViewController") as! LoginScreenViewController

        var destinationDS = destination.router?.dataStore
        passData(dataSource: dataStore, destination: &destinationDS)
        viewController?.navigationController?.pushViewController(destination, animated: true)
    }
    
    private func passData(dataSource: FirstScreenDataStore?,
                          destination: inout LoginScreenDataStore?) {
        destination?.user = dataSource?.user
    }
}

