//
//  FirstScreenPresenter.swift
//  Rager Streak
//
//  Created by guilherme.martinelli on 16/11/20.
//  Copyright (c) 2020 guilherme.martinelli. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//

import UIKit

protocol FirstScreenPresentationLogic {
    func setupButton()
}

class FirstScreenPresenter: FirstScreenPresentationLogic {
    
  weak var viewController: FirstScreenDisplayLogic?
    
    func setupButton() {
        let color = UIColor(hexString: "7A4DDF").cgColor
        let viewModel = FirstScreen.Model.RSButton(borderColor: color, borderWidth: 1)
        viewController?.setupButton(buttonViewModel: viewModel)
    }
}
