//
//  FirstScreenInteractor.swift
//  Rager Streak
//
//  Created by guilherme.martinelli on 16/11/20.
//  Copyright (c) 2020 guilherme.martinelli. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//

import UIKit

protocol FirstScreenBusinessLogic
{

}

protocol FirstScreenDataStore {
     var user: FirstScreen.Model.User? { get set }
}

class FirstScreenInteractor: FirstScreenBusinessLogic, FirstScreenDataStore {
    
    var user: FirstScreen.Model.User?
    var presenter: FirstScreenPresentationLogic?

    // MARK: Do something
  
}
