//
//  NewRagerGameViewController.swift
//  Rager Streak
//
//  Created by guilherme.martinelli on 22/12/20.
//  Copyright (c) 2020 guilherme.martinelli. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//

import UIKit

protocol NewRagerGameDisplayLogic: class
{

}

class NewRagerGameViewController: UIViewController, NewRagerGameDisplayLogic
{
//  var interactor: NewRagerGameBusinessLogic?
//  var router: (NSObjectProtocol & NewRagerGameRoutingLogic & NewRagerGameDataPassing)?

  // MARK: Object lifecycle
  
  override init(nibName nibNameOrNil: String?, bundle nibBundleOrNil: Bundle?)
  {
    super.init(nibName: nibNameOrNil, bundle: nibBundleOrNil)
    setup()
  }
  
  required init?(coder aDecoder: NSCoder)
  {
    super.init(coder: aDecoder)
    setup()
  }
  
  // MARK: Setup
  
  private func setup()
  {
//    let viewController = self
//    let interactor = NewRagerGameInteractor()
//    let presenter = NewRagerGamePresenter()
//    let router = NewRagerGameRouter()
//    viewController.interactor = interactor
//    viewController.router = router
//    interactor.presenter = presenter
//    presenter.viewController = viewController
//    router.viewController = viewController
//    router.dataStore = interactor
  }
  
  // MARK: Routing
  
  // MARK: View lifecycle
  
  override func viewDidLoad()
  {
    super.viewDidLoad()
    doSomething()
    setupNavBar()
    self.title = "Novo Rager"
  }
  
  // MARK: Do something
  
  //@IBOutlet weak var nameTextField: UITextField!
  
  func doSomething()
  {
    
  }

}
extension NewRagerGameViewController {
    func setupNavBar() {
        self.navigationItem.leftBarButtonItem = self.navigationController?.setupLeftButtonNavBar()
    }
}
