//
//  RagersViewController.swift
//  Rager Streak
//
//  Created by guilherme.martinelli on 15/12/20.
//  Copyright (c) 2020 guilherme.martinelli. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//

import UIKit

protocol RagersDisplayLogic: class {
  func displaySomething(viewModel: Ragers.Something.ViewModel)
}

class RagersViewController: UIViewController, RagersDisplayLogic {

    @IBOutlet weak var tableViewRagers: UITableView!
    @IBOutlet weak var searchRagers: UISearchBar!
    var interactor: RagersBusinessLogic?
  var router: (NSObjectProtocol & RagersRoutingLogic & RagersDataPassing)?

  // MARK: Object lifecycle
  
  override init(nibName nibNameOrNil: String?, bundle nibBundleOrNil: Bundle?)
  {
    super.init(nibName: nibNameOrNil, bundle: nibBundleOrNil)
    setup()
  }
  
  required init?(coder aDecoder: NSCoder)
  {
    super.init(coder: aDecoder)
    setup()
  }
  
  // MARK: Setup
  
  private func setup()
  {
    let viewController = self
    let interactor = RagersInteractor()
    let presenter = RagersPresenter()
    let router = RagersRouter()
    viewController.interactor = interactor
    viewController.router = router
    interactor.presenter = presenter
    presenter.viewController = viewController
    router.viewController = viewController
    router.dataStore = interactor
  }
  
  // MARK: View lifecycle
    var arrayOfCellData = [Ragers.CellData]()
  override func viewDidLoad()
  {
    super.viewDidLoad()
    doSomething()
    setupSearchBar()
    self.view.backgroundColor = RSColor().blackColor()
    arrayOfCellData = [Ragers.CellData(image: #imageLiteral(resourceName: "travis"), name: "Guilherme Borges", game: "Jogo: Valorant", rages: "10 Rages em partidas"),
    Ragers.CellData(image: #imageLiteral(resourceName: "travis"), name: "Lucas Yuji", game: "Jogo: Valorant", rages: "15 Rages em partidas"),
    Ragers.CellData(image: #imageLiteral(resourceName: "travis"), name: "Lucas Yuji", game: "Jogo: League Of Legends", rages: "15 Rages em partidas")]
    tableViewRagers.delegate = self
    tableViewRagers.dataSource = self
  }
  
  // MARK: Do something
    private func setupSearchBar() {
        if let textFieldSearchBar = searchRagers.value(forKey: "searchField") as? UITextField {
            textFieldSearchBar.textColor = .white
        }
        
    }
  func doSomething()
  {
    let request = Ragers.Something.Request()
    interactor?.doSomething(request: request)
    self.navigationController?.setNavigationBarHidden(false, animated: false)
  }
  
  func displaySomething(viewModel: Ragers.Something.ViewModel)
  {
    //nameTextField.text = viewModel.name
  }
}

extension RagersViewController: UITableViewDataSource, UITableViewDelegate {
    func tableView(_ tableView: UITableView, numberOfRowsInSection section: Int) -> Int {
        return arrayOfCellData.count
    }
    
    func tableView(_ tableView: UITableView, cellForRowAt indexPath: IndexPath) -> UITableViewCell {
        let cell = Bundle.main.loadNibNamed("TableViewCell", owner: self, options: nil)?.first as! TableViewCell
        cell.imageUser.image = arrayOfCellData[indexPath.row].image
        cell.imageUser.makeRounded()
        cell.labelName.text = arrayOfCellData[indexPath.row].name
        cell.labelGame.text = arrayOfCellData[indexPath.row].game
        cell.labelRages.text = arrayOfCellData[indexPath.row].rages
        
        return cell
    }
    func tableView(_ tableView: UITableView, heightForRowAt indexPath: IndexPath) -> CGFloat {
            return 88
        }
    
}
