//
//  NewRagerInteractor.swift
//  Rager Streak
//
//  Created by guilherme.martinelli on 17/12/20.
//  Copyright (c) 2020 guilherme.martinelli. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//

import UIKit

protocol NewRagerBusinessLogic
{
  
}

protocol NewRagerDataStore
{
  
}

class NewRagerInteractor: NewRagerBusinessLogic, NewRagerDataStore
{

    
  
}
