//
//  NewRagerViewController.swift
//  Rager Streak
//
//  Created by guilherme.martinelli on 17/12/20.
//  Copyright (c) 2020 guilherme.martinelli. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//

import UIKit

protocol NewRagerDisplayLogic: class
{
}

class NewRagerViewController: UIViewController, NewRagerDisplayLogic
{
    @IBOutlet weak var inputName: RSTextField!
    
    @IBOutlet weak var labelCustom: UILabel!
    
    var interactor: NewRagerBusinessLogic?
    var router: (NSObjectProtocol & NewRagerRoutingLogic & NewRagerDataPassing)?
    
    // MARK: Object lifecycle
    
    override init(nibName nibNameOrNil: String?, bundle nibBundleOrNil: Bundle?)
    {
        super.init(nibName: nibNameOrNil, bundle: nibBundleOrNil)
        setup()
    }
    
    required init?(coder aDecoder: NSCoder)
    {
        super.init(coder: aDecoder)
        setup()
    }
    
    // MARK: Setup
    
    private func setup()
    {
        let viewController = self
        let interactor = NewRagerInteractor()
        //    let presenter = NewRagerPresenter()
        let router = NewRagerRouter()
        viewController.interactor = interactor
        viewController.router = router
        //    interactor.presenter = presenter
        //    presenter.viewController = viewController
        router.viewController = viewController
        router.dataStore = interactor
    }
    
    // MARK: Routing
    
    // MARK: View lifecycle
    
    override func viewDidLoad()
    {
        super.viewDidLoad()
        self.tabBarController?.tabBar.isHidden = true
        self.title = "Novo Rager"
        setupNavBar()
    }
    
    @IBAction func nextScreen(_ sender: Any) {
        router?.routeToNewRagerGame()
    }
    
}
extension NewRagerViewController {
    func setupNavBar() {
        self.navigationItem.leftBarButtonItem = self.navigationController?.setupLeftButtonNavBar()
    }
    
    
}

