//
//  HomeViewController.swift
//  Rager Streak
//
//  Created by guilherme.martinelli on 20/11/20.
//  Copyright (c) 2020 guilherme.martinelli. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//

import UIKit

protocol HomeDisplayLogic: class
{
  func displaySomething(viewModel: Home.Something.ViewModel)
}

class HomeViewController: UIViewController, HomeDisplayLogic, UITabBarDelegate
{
    var interactor: HomeBusinessLogic?
    var router: (NSObjectProtocol & HomeRoutingLogic & HomeDataPassing)?
    
    // MARK: Object lifecycle
  
    
    @IBOutlet weak var viewDefeats: UIView!
    @IBOutlet weak var viewVictories: UIView!
    @IBOutlet weak var viewRages: UIView!
    @IBOutlet weak var userImage: UIImageView!
    override init(nibName nibNameOrNil: String?, bundle nibBundleOrNil: Bundle?)
  {
    super.init(nibName: nibNameOrNil, bundle: nibBundleOrNil)
    setup()
  }
  
  required init?(coder aDecoder: NSCoder)
  {
    super.init(coder: aDecoder)
    setup()
  }
  
  // MARK: Setup
  
  private func setup()
  {
    let viewController = self
    let interactor = HomeInteractor()
    let presenter = HomePresenter()
    let router = HomeRouter()
    viewController.interactor = interactor
    viewController.router = router
    interactor.presenter = presenter
    presenter.viewController = viewController
    router.viewController = viewController
    router.dataStore = interactor
  }
  
  // MARK: View lifecycle
  
  override func viewDidLoad()
  {
    super.viewDidLoad()
    self.navigationController?.setNavigationBarHidden(false, animated: false)
    self.view.backgroundColor = RSColor().blackColor()
    self.title = "Travis Scott"
    self.navigationController?.navigationBar.titleTextAttributes = [NSAttributedString.Key.foregroundColor:UIColor.white]
    setupNavBar()
    viewRages.setupViews(circleView: viewRages, color: RSColor().purpleColor())
    viewDefeats.setupViews(circleView: viewDefeats, color: RSColor().redColor())
    viewVictories.setupViews(circleView: viewVictories, color: RSColor().greenColor())

    userImage.makeRounded()
    doSomething()
    tabBarController?.tabBar.isHidden = false
    }

    override func viewDidAppear(_ animated: Bool) {
        super.viewDidAppear(false)
        tabBarController?.tabBar.isHidden = false
    }

    func doSomething()
    {
        let request = Home.Something.Request()
        interactor?.doSomething(request: request)
    }
    
    func displaySomething(viewModel: Home.Something.ViewModel)
    {
        //nameTextField.text = viewModel.name
    }
    
    func tabBar(_ tabBar: UITabBar, didSelect item: UITabBarItem) {
        print("teste")
    }
}

extension HomeViewController {
    func setupNavBar() {
        self.navigationItem.rightBarButtonItem = self.navigationController?.setupRightButtonNavBar()
        self.navigationItem.leftBarButtonItem = self.navigationController?.setupLeftButtonNavBar()
    }
}
