//
//  SecondScreenPresenter.swift
//  Rager Streak
//
//  Created by guilherme.martinelli on 16/11/20.
//  Copyright (c) 2020 guilherme.martinelli. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//

import UIKit

protocol SecondScreenPresentationLogic
{
    func changeLabel(string: String)
}

class SecondScreenPresenter: SecondScreenPresentationLogic
{
    func changeLabel(string: String) {
        viewController?.changeLabel(string: string)
    }
    
  weak var viewController: SecondScreenDisplayLogic?
  
  // MARK: Do something

}
