//
//  SecondScreenViewController.swift
//  Rager Streak
//
//  Created by guilherme.martinelli on 16/11/20.
//  Copyright (c) 2020 guilherme.martinelli. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//

import UIKit

protocol SecondScreenDisplayLogic: class {
    func changeLabel(string: String)
}

class SecondScreenViewController: UIViewController, SecondScreenDisplayLogic {
    
    @IBOutlet weak var label: UILabel!
    
    var interactor: SecondScreenBusinessLogic?
    var router: (NSObjectProtocol & SecondScreenRoutingLogic & SecondScreenDataPassing)?
    
    // MARK: Object lifecycle
    
    override init(nibName nibNameOrNil: String?, bundle nibBundleOrNil: Bundle?)
    {
        super.init(nibName: nibNameOrNil, bundle: nibBundleOrNil)
        setup()
    }
    
    required init?(coder aDecoder: NSCoder)
    {
        super.init(coder: aDecoder)
        setup()
        
    }
    
    // MARK: Setup
    
    private func setup()
    {
        let viewController = self
        let interactor = SecondScreenInteractor()
        let presenter = SecondScreenPresenter()
        let router = SecondScreenRouter()
        viewController.interactor = interactor
        viewController.router = router
        interactor.presenter = presenter
        presenter.viewController = viewController
        router.viewController = viewController
        router.dataStore = interactor
    }
    
    // MARK: Routing
    
    override func prepare(for segue: UIStoryboardSegue, sender: Any?)
    {
        if let scene = segue.identifier {
            let selector = NSSelectorFromString("routeTo\(scene)WithSegue:")
            if let router = router, router.responds(to: selector) {
                router.perform(selector, with: segue)
            }
        }
    }
    
    // MARK: View lifecycle
    
    override func viewDidLoad()
    {
        super.viewDidLoad()
        self.navigationController?.setNavigationBarHidden(false, animated: false)
        interactor?.applyTextOnLabel()
    }
    
    func changeLabel(string: String) {
        label.text = string
    }
}
