//
//  SecondScreenInteractor.swift
//  Rager Streak
//
//  Created by guilherme.martinelli on 16/11/20.
//  Copyright (c) 2020 guilherme.martinelli. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//

import UIKit

protocol SecondScreenBusinessLogic
{
    func setupButtonAndInputs()
}

protocol SecondScreenDataStore
{
    var user: LoginScreen.Model.User? { get set }
}

class SecondScreenInteractor: SecondScreenBusinessLogic, SecondScreenDataStore
{
    
    var user: LoginScreen.Model.User?
    
    var presenter: SecondScreenPresentationLogic?
    
    // MARK: Do something
    func setupButtonAndInputs() {
        presenter?.setupButtonAndInputs()
    }
    
}
