//
//  SecondScreenPresenter.swift
//  Rager Streak
//
//  Created by guilherme.martinelli on 16/11/20.
//  Copyright (c) 2020 guilherme.martinelli. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//

import UIKit

protocol SecondScreenPresentationLogic
{
    func setupButtonAndInputs()
}

class SecondScreenPresenter: SecondScreenPresentationLogic
{
    
    weak var viewController: SecondScreenDisplayLogic?
    // MARK: Do something
    func setupButtonAndInputs() {
        let color = UIColor(hexString: "7A4DDF").cgColor
        let backgroundColor = UIColor(hexString: "131313")
        let viewModelButton = LoginScreen.Model.RSButton(borderColor: color, borderWidth: 1)
        let viewModelInput = LoginScreen.Model.RSInput(attributedPlaceholder: NSAttributedString(string: "Digite seu usuário", attributes: [NSAttributedString.Key.foregroundColor : UIColor.gray.withAlphaComponent(0.9)]))
        viewController?.setupButtonAndInput(viewModelButton: viewModelButton,
                                            viewModelInput: viewModelInput)
    }
    
}
