//
//  SecondScreenRouter.swift
//  Rager Streak
//
//  Created by guilherme.martinelli on 16/11/20.
//  Copyright (c) 2020 guilherme.martinelli. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//

import UIKit

@objc protocol SecondScreenRoutingLogic
{
    func routeToSuccess()
}

protocol SecondScreenDataPassing
{
    var dataStore: SecondScreenDataStore? { get }
}

class SecondScreenRouter: NSObject, SecondScreenRoutingLogic, SecondScreenDataPassing
{
    weak var viewController: SecondScreenViewController?
    var dataStore: SecondScreenDataStore?
    
    func routeToSuccess() {
        let destination: HomeViewController = UIStoryboard(name: "Main", bundle: nil).instantiateViewController(withIdentifier: "HomeViewController") as! HomeViewController
        
//        var destinationDS = destination.router?.dataStore
        viewController?.navigationController?.pushViewController(destination, animated: true)
    }
}
